apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-app
  template:
    metadata:
      labels:
        app: platform-app
    spec:
      containers:
        - name: app
          image: ghcr.io/dhia-03/platform-project:latest
          ports:
            - containerPort: 5000
