apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-app
  template:
    metadata:
      labels:
        app: platform-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: app
          image: ghcr.io/dhia-03/platform-project:844ba77dff63f76c495544ce990cbf0cc7377469
          ports:
            - containerPort: 5000
